In [4]:
import numpy 
from scipy import stats

In [5]:
years = numpy.array([2745997, 2782353, 1903713, 2202779, 1988858, 1363806, 1266800, 1311604, 1396967, 1477301, 1502477, 1457376, 1479637, 1610122, 1713947, 1761687, 1788948, 1796629, 1902084, 1895822, 1942683, 1940579, 1888729, 1690307, 1604344, 1481074, 1436514, 1398253, 1304087])

In [6]:
years

array([2745997, 2782353, 1903713, 2202779, 1988858, 1363806, 1266800,
       1311604, 1396967, 1477301, 1502477, 1457376, 1479637, 1610122,
       1713947, 1761687, 1788948, 1796629, 1902084, 1895822, 1942683,
       1940579, 1888729, 1690307, 1604344, 1481074, 1436514, 1398253,
       1304087])

In [7]:
stats.zscore(years) # фильтр z оценки

array([ 2.74836085,  2.84626003,  0.48026429,  1.28558716,  0.70954216,
       -0.97359356, -1.23481064, -1.11416274, -0.88429784, -0.667975  ,
       -0.60018124, -0.7216289 , -0.66168464, -0.31031553, -0.03073628,
        0.09781766,  0.17122589,  0.19190924,  0.47587773,  0.45901546,
        0.58520244,  0.5795368 ,  0.43991548, -0.09439391, -0.32587449,
       -0.65781509, -0.77780595, -0.88083491, -1.13440447])

In [9]:
abs_zscore = numpy.abs(stats.zscore(years))

In [10]:
abs_zscore #  по модулю

array([2.74836085, 2.84626003, 0.48026429, 1.28558716, 0.70954216,
       0.97359356, 1.23481064, 1.11416274, 0.88429784, 0.667975  ,
       0.60018124, 0.7216289 , 0.66168464, 0.31031553, 0.03073628,
       0.09781766, 0.17122589, 0.19190924, 0.47587773, 0.45901546,
       0.58520244, 0.5795368 , 0.43991548, 0.09439391, 0.32587449,
       0.65781509, 0.77780595, 0.88083491, 1.13440447])

In [17]:
years[abs_zscore > 3] # отклонение больше чем на 3 стандартных отклонения

array([], dtype=int32)

In [19]:
years

array([2745997, 2782353, 1903713, 2202779, 1988858, 1363806, 1266800,
       1311604, 1396967, 1477301, 1502477, 1457376, 1479637, 1610122,
       1713947, 1761687, 1788948, 1796629, 1902084, 1895822, 1942683,
       1940579, 1888729, 1690307, 1604344, 1481074, 1436514, 1398253,
       1304087])

In [20]:
[abs_zscore]

[array([2.74836085, 2.84626003, 0.48026429, 1.28558716, 0.70954216,
        0.97359356, 1.23481064, 1.11416274, 0.88429784, 0.667975  ,
        0.60018124, 0.7216289 , 0.66168464, 0.31031553, 0.03073628,
        0.09781766, 0.17122589, 0.19190924, 0.47587773, 0.45901546,
        0.58520244, 0.5795368 , 0.43991548, 0.09439391, 0.32587449,
        0.65781509, 0.77780595, 0.88083491, 1.13440447])]

In [22]:
numpy.mean(years[abs_zscore < 3]) #  среднее значение без выбросов (1713947 - 1761687, т.у. 2008-2009 годы)

1725361.2758620689

In [25]:
numpy.quantile(years, 0.25) # 25 квантиль это 2005 год.


1457376.0

In [12]:
numpy.quantile(years, 0.75) # 75 квантиль 2012 год.

1902084.0

In [32]:
numpy.quantile(years, 0.5)  # медиана это 2007-2008 годы.(середина )


1690307.0

In [18]:
numpy.quantile(years, 0.75)


1902084.0

In [19]:
numpy.quantile(years, 0.25)

1457376.0

In [20]:
IQR = (numpy.quantile(years, 0.75) - numpy.quantile(years, 0.25)) # Межкватильный размах

In [21]:
IQR 

444708.0

In [28]:
quantile25 = numpy.quantile(years, 0.25) 
quantile75  = numpy.quantile(years, 0.75)


In [30]:
quantile25 


1457376.0

In [31]:
quantile75

1902084.0

In [59]:
lower_bound = quantile25 - 1.5*IQR

In [60]:
lower_bound # минимум б выброса нижнего нет.

790314.0

In [46]:
hight_bound = quantile75 + 1.5*IQR

In [47]:
hight_bound # максимум , выброс это 1950 и 1960 гг.

2569146.0

In [72]:
years[( years<lower_bound) |(years>hight_bound)] # нетипичные годы с точки зрения рождаемости. 1950 и 1960 годы.


array([2745997, 2782353])

In [76]:
len(years[(years<lower_bound)|(years>hight_bound)]) # количество 2 шт.

2

In [79]:
years[abs_zscore >3]

array([], dtype=int32)

In [81]:
numpy.nan = years[abs_zscore >3]

In [82]:
numpy.nan

array([], dtype=int32)

In [84]:
years[numpy.isnan(years)]

array([], dtype=int32)

In [89]:
numpy.nanmean(years) = years[numpy.isnan(years)]

SyntaxError: cannot assign to function call here. Maybe you meant '==' instead of '='? (4114279157.py, line 1)

In [86]:
numpy.nanmean(years) #  среднее значение в ряду, игнорирующее значения nan.

1725361.2758620689

In [ ]:
numpy.nanmax(years)=years[numpy.isnan(years)]


In [87]:
numpy.nanmax(years) #  max. (заменить или на среднее или на max)

2782353